Fixed code

diff --git a/.github/workflows/docker-ci-cd.yml b/.github/workflows/docker-ci-cd.yml
--- a/.github/workflows/docker-ci-cd.yml
+++ b/.github/workflows/docker-ci-cd.yml
@@ -12,6 +12,8 @@ jobs:
                   docker build . --file Dockerfile --tag hackthenumber
                   docker login -u ${{secrets.USERNAME}} -p ${{secrets.TOKEN}}
                   docker tag hackthenumber ${{secrets.USERNAME}}/hackthenumber
+                  docker push ${{secrets.USERNAME}}/hackthenumber && echo "✅ Deployed to Docker Hub" || ( echo "❌ Deployment to Docker Hub failed" && exit 1 )
+
                   
    docker-test:
         runs-on: ubuntu-latest
@@ -20,6 +22,7 @@ jobs:
            - uses: actions/checkout@v3
            - name: Test image presence
              run: |
+               docker pull ${{secrets.USERNAME}}/hackthenumber
                docker image inspect ${{secrets.USERNAME}}/hackthenumber
                if [[ $? -eq 1 ]]; then
                   echo "❌ Image not found!"
@@ -37,12 +40,4 @@ jobs:
                   else
                      echo "✅ Image response is 200!"
                   fi
-   docker-deploy:
-         runs-on: ubuntu-latest
-         needs: docker-test
-         steps:
-            - uses: actions/checkout@v3
-            - name: Deploy to docker hub
-              run: |
-                docker push ${{secrets.USERNAME}}/hackthenumber && echo "✅ Deployed to Docker Hub" || echo "❌ Deployment to Docker Hub failed"
 
